# SWE546 Final Project

Tuğba Demiryürek

I use MovieLens data for my project. 

First I read the data and display the important parts as tables.

In [16]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy as sc
import scipy.linalg as la

rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratingsAll = pd.read_table('data/ratings.dat', sep='::', header=None, names=rnames, engine='python')
ratings = ratingsAll[:500]

Ratings data:

In [17]:
ratings

     user_id  movie_id  rating  timestamp
0          1      1193       5  978300760
1          1       661       3  978302109
2          1       914       3  978301968
3          1      3408       4  978300275
4          1      2355       5  978824291
5          1      1197       3  978302268
6          1      1287       5  978302039
7          1      2804       5  978300719
8          1       594       4  978302268
9          1       919       4  978301368
10         1       595       5  978824268
11         1       938       4  978301752
12         1      2398       4  978302281
13         1      2918       4  978302124
14         1      1035       5  978301753
15         1      2791       4  978302188
16         1      2687       3  978824268
17         1      2018       4  978301777
18         1      3105       5  978301713
19         1      2797       4  978302039
20         1      2321       3  978302205
21         1       720       3  978300760
22         1      1270       5  978300055
23         1       527       5  978824195
24         1      2340       3  978300103
25         1        48       5  978824351
26         1      1097       4  978301953
27         1      1721       4  978300055
28         1      1545       4  978824139
29         1       745       3  978824268
..       ...       ...     ...        ...
470        6      1043       4  978236219
471        6      2858       1  978236809
472        6       377       3  978236383
473        6       590       3  978237232
474        6       595       4  978237511
475        6       597       5  978239019
476        6       383       4  978237909
477        6      2506       3  978236975
478        6      3524       3  978236719
479        6      1566       4  978237570
480        6      1569       4  978238948
481        6      2006       4  978236122
482        6      2081       4  978236567
483        6      2082       3  978236975
484        6      3600       3  978237813
485        6      3604       5  978237767
486        6      2802       4  978236612
487        6      3534       4  978236219
488        6      3536       5  978238230
489        6      1210       3  978236219
490        6      3753       5  978238195
491        6      3682       3  978238036
492        6      2017       3  978237813
493        6      3685       3  978236519
494        6      3610       3  978237813
495        6      1296       3  978236519
496        6       838       4  978237444
497        6      1007       3  978238036
498        6      1947       5  978237767
499        6      2966       5  978237273

[500 rows x 4 columns]

In [18]:
mColumns  = ['movie_id', 'title', 'genres']
moviesAll  = pd.read_table(u'data/movies.dat', sep='::', header=None, names=mColumns, engine = 'python')
movies = moviesAll[:500]

Movies data:

In [19]:
movies

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
470,474,In the Line of Fire (1993),Action|Thriller
471,475,In the Name of the Father (1993),Drama
472,476,"Inkwell, The (1994)",Comedy|Drama
473,477,What's Love Got to Do with It? (1993),Drama
474,478,Jimmy Hollywood (1994),Comedy
475,479,Judgment Night (1993),Action
476,480,Jurassic Park (1993),Action|Adventure|Sci-Fi
477,481,Kalifornia (1993),Drama|Thriller
478,482,Killing Zoe (1994),Thriller
479,483,King of the Hill (1993),Drama
480,484,Lassie (1994),Adventure|Children's
481,485,Last Action Hero (1993),Action|Comedy
482,486,Life with Mikey (1993),Comedy
483,487,Lightning Jack (1994),Comedy|Western
484,488,M. Butterfly (1993),Drama
485,489,Made in America (1993),Comedy
486,490,Malice (1993),Thriller
487,491,"Man Without a Face, The (1993)",Drama
488,492,Manhattan Murder Mystery (1993),Comedy|Mystery
489,493,Menace II Society (1993),Action|Crime|Drama
490,494,Executive Decision (1996),Action|Thriller
491,495,In the Realm of the Senses (Ai no corrida) (1976),Drama
492,496,What Happened Was... (1994),Comedy|Drama|Romance
493,497,Much Ado About Nothing (1993),Comedy|Romance
494,498,Mr. Jones (1993),Drama|Romance
495,499,Mr. Wonderful (1993),Comedy|Romance
496,500,Mrs. Doubtfire (1993),Comedy
497,501,Naked (1993),Drama
498,502,"Next Karate Kid, The (1994)",Action|Children's
499,503,"New Age, The (1994)",Drama

# Stochastic Gradient Descent

I use Stochastic Gradient Descent as my algorithm in the recommendation system.

In [20]:
user = np.matrix(ratings.user_id).T
movie = np.matrix(ratings.movie_id).T
rating = np.matrix(ratings.rating).T

Ys = np.hstack([rating,user,movie])
MovieMax = 0
UserMax = 0
for i in range (Ys.shape[0]):
    if(Ys[i,2]>MovieMax):
        MovieMax = Ys[i,2]
    if(Ys[i,1]>UserMax):
        UserMax = Ys[i,1]

userinitial = np.matrix([0]*(UserMax+1)).T 
movieinitial = np.matrix([0]*(MovieMax+1)) 
Y = userinitial*movieinitial
M = Y
Ysize = Ys.shape[0]

A = np.mat(np.random.rand(UserMax+1, 1))
B = np.mat(np.random.rand(1, MovieMax+1))

In [22]:
EPOCH = 5
Eta = 0.1
eta = Eta

for i in range(EPOCH):
    E = np.array(M)*np.array(Y - A*B)

    for k in range(Ysize):
        u = Ys[k,1]
        m = Ys[k,2]
        
        err = Ys[k,0] - A[u,0]*B[0,m]
        
        temp_A = A[u,0] + eta*err*B[0,m]
        B[0,m]   = B[0,m] + eta*err*A[u,0]
        A[u,0]   = temp_A
    
    eta = Eta*1./(i+1)

In [30]:
res = A*B
for j in range (6):
    
    userinfo = [(0,0)]
    for m in range (MovieMax):
        movieTuple = (res[j,m],m)
        userinfo.append(movieTuple)
    
    userinfo = sorted(userinfo, key=lambda tup: tup[0], reverse=True)     
    
    print("Movie for user " , j , " : ")
    for n in range(5):
        print (userinfo[n])

Movie for user  0  :
(1.7159219410329516, 1250)
(1.6408068955227593, 3083)
(1.6097433394643688, 1175)
(1.5834073207734338, 2337)
(1.5797324306668148, 1089)
Movie for user  1  :
(6.5175769423329211, 1250)
(6.2322678749840836, 3083)
(6.1142793395666999, 1175)
(6.0142473835270458, 2337)
(6.0002890684943173, 1089)
Movie for user  2  :
(6.5064561035892146, 1250)
(6.2216338546021976, 3083)
(6.1038466411619217, 1175)
(6.0039853680711879, 2337)
(5.9900508698912542, 1089)
Movie for user  3  :
(5.9980818972586967, 1250)
(5.7355138958173093, 3083)
(5.6269298461570134, 1175)
(5.5348711148251724, 2337)
(5.5220253720813872, 1089)
Movie for user  4  :
(6.4106602927238647, 1250)
(6.1300315367628215, 3083)
(6.0139785272334665, 1175)
(5.9155875309689288, 2337)
(5.9018581930991392, 1089)
Movie for user  5  :
(5.4941014712096248, 1250)
(5.2535953781416058, 3083)
(5.1541349510905548, 1175)
(5.0698113256530437, 2337)
(5.0580449284420173, 1089)